# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mohammad Varmazyar
email: mrvarmazyar[at]gmail.com
description:  My name is Mohammad. It's roughly pronounced as [Mo:h@mm@d] [v@rm@zya:r] in IPA ASCII transcription. 
              It is a Persian name, natively written as محمد ورمزیار. I was born and grew up in Iran. 
              Currently, I am a DevOps Team Leader/Engineer at the Alibaba Travels Company in Iran. 
              Previously I was a DevOps and Cloud Engineer at PersianGiG, making technical life easier with container orchestration and cloud system implementations in motherland. 
              My long-term goal since late last century has been to make fully automated infrastructures in big companies in the world, 
              though these days my focus is not limited to new technologies and concepts anymore.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://varmazyar.me" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
